version: '3'
services:
  
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - location_db

  location_db:
    image: mongo:3.0.2
    ports:
      - "27017:27017"